image: node:20

before_script:
  # the following script is taken from https://docs.gitlab.com/ee/ci/ssh_keys/README.html
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy:
#   cache:
#     paths:
#       - node_modules/
  script:
    # - apk add git # Uncomment this if you're using small docker images like alpine and have lastUpdated enabled
    - npm install
    - npm run docs:build
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r public/* root@zjk.irminsul.top:/opt/1panel/apps/openresty/openresty/www/sites/www.irminsul.top/index/
#   artifacts:
#     paths:
#       - public
  only:
    - main